"""Add fields for image and lab files to Case model

Revision ID: 25b7e0fd70f5
Revises: 2fe7791d6842
Create Date: 2023-11-23 13:15:37.146087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25b7e0fd70f5'
down_revision = '2fe7791d6842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_age', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('patient_sex', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('chief_complaint', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('medical_history', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('current_medications', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image_files', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('lab_files', sa.String(length=255), nullable=True))
        batch_op.drop_column('body')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.TEXT(), nullable=True))
        batch_op.drop_column('lab_files')
        batch_op.drop_column('image_files')
        batch_op.drop_column('current_medications')
        batch_op.drop_column('medical_history')
        batch_op.drop_column('chief_complaint')
        batch_op.drop_column('patient_sex')
        batch_op.drop_column('patient_age')

    # ### end Alembic commands ###
