"""new fields in user model

Revision ID: 5c845ab88d74
Revises: f87796e9aa7c
Create Date: 2023-11-20 11:12:40.113708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c845ab88d74'
down_revision = 'f87796e9aa7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('medical_degree', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('speciality', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('licenses', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('licenses')
        batch_op.drop_column('speciality')
        batch_op.drop_column('medical_degree')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
