"""Add search_vector to Case

Revision ID: c2da1c30f1dc
Revises: 5b797fb7f890
Create Date: 2023-12-05 13:15:17.568684

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'c2da1c30f1dc'
down_revision = '5b797fb7f890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('search_vector')

    # ### end Alembic commands ###
